// <auto-generated />
using System;
using System.Collections.Generic;
using FiapAgro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiapAgro.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiapAgro.Domain.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Probabilidade")
                        .HasColumnType("double precision");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("tipo_alerta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("alertas", (string)null);

                    b.HasDiscriminator<string>("tipo_alerta").HasValue("Alerta");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FiapAgro.Domain.Entities.Propriedade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AreaHectares")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Localizacao", "FiapAgro.Domain.Entities.Propriedade.Localizacao#Coordenada", b1 =>
                        {
                            b1.Property<double>("Latitude")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("double precision")
                                .HasDefaultValue(0.0)
                                .HasColumnName("localizacao_lat");

                            b1.Property<double>("Longitude")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("double precision")
                                .HasDefaultValue(0.0)
                                .HasColumnName("localizacao_lng");
                        });

                    b.HasKey("Id");

                    b.ToTable("propriedades", (string)null);
                });

            modelBuilder.Entity("FiapAgro.Domain.Entities.AlertaEnchente", b =>
                {
                    b.HasBaseType("FiapAgro.Domain.Entities.Alerta");

                    b.Property<double>("VolumeMM")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Enchente");
                });

            modelBuilder.Entity("FiapAgro.Domain.Entities.AlertaErosao", b =>
                {
                    b.HasBaseType("FiapAgro.Domain.Entities.Alerta");

                    b.Property<double>("InclinacaoSolo")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Erosao");
                });

            modelBuilder.Entity("FiapAgro.Domain.Entities.AlertaGeada", b =>
                {
                    b.HasBaseType("FiapAgro.Domain.Entities.Alerta");

                    b.Property<double>("TemperaturaMinima")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Geada");
                });

            modelBuilder.Entity("FiapAgro.Domain.Entities.AlertaPraga", b =>
                {
                    b.HasBaseType("FiapAgro.Domain.Entities.Alerta");

                    b.Property<string>("CulturaAfetada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EspeciePraga")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasDiscriminator().HasValue("Praga");
                });

            modelBuilder.Entity("FiapAgro.Domain.Entities.AlertaSeca", b =>
                {
                    b.HasBaseType("FiapAgro.Domain.Entities.Alerta");

                    b.Property<int>("DiasSemChuva")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Seca");
                });
#pragma warning restore 612, 618
        }
    }
}
